# Generated by Django 4.0.2 on 2022-03-07 13:48

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InitialCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        default=django.contrib.gis.geos.point.Point(0, 0), srid=4326
                    ),
                ),
                ("storage_level", models.FloatField()),
                ("slow_flow_rate", models.FloatField()),
                ("fast_flow_rate", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="NoaaForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        default=django.contrib.gis.geos.point.Point(0, 0), srid=4326
                    ),
                ),
                ("precipitation", models.FloatField()),
                ("min_temperature", models.FloatField()),
                ("max_temperature", models.FloatField()),
                ("wind_u", models.FloatField()),
                ("wind_v", models.FloatField()),
                ("relative_humidity", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="RiverFlowCalculationOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prediction_date", models.DateTimeField()),
                ("forecast_time", models.DateTimeField()),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        default=django.contrib.gis.geos.point.Point(0, 0), srid=4326
                    ),
                ),
                ("rain_fall", models.FloatField()),
                ("potential_evapotranspiration", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="ZentraDevice",
            fields=[
                (
                    "device_sn",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "device_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("height", models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="ZentraReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("relative_humidity", models.FloatField()),
                ("precipitation", models.FloatField()),
                ("air_temperature", models.FloatField()),
                ("wind_speed", models.FloatField()),
                ("wind_direction", models.FloatField()),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculations.zentradevice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RiverFlowPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prediction_index", models.IntegerField(default=0)),
                ("river_flow", models.FloatField()),
                (
                    "calculation_output",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculations.riverflowcalculationoutput",
                    ),
                ),
            ],
        ),
    ]
