# Generated by Django 4.0.1 on 2022-02-02 14:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ZentraDevice",
            fields=[
                (
                    "device_sn",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "device_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("height", models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="NoaaForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("precipitation", models.FloatField()),
                ("min_temperature", models.FloatField()),
                ("max_temperature", models.FloatField()),
                ("wind_u", models.FloatField()),
                ("wind_v", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="ZentraReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("precipitation", models.FloatField()),
                ("air_temperature", models.FloatField()),
                ("wind_speed", models.FloatField()),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculations.zentradevice",
                    ),
                ),
                ("relative_humidity", models.FloatField()),
                ("wind_direction", models.FloatField()),
            ],
        ),
    ]
