# Generated by Django 4.0.2 on 2022-02-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="noaaforecast",
            name="relative_humidity",
            field=models.FloatField(default=0),
        ),
    ]
