# Generated by Django 4.0.3 on 2022-04-07 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "calculations",
            "0001_squashed_0017_remove_aggregateddepthprediction_tile_size_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="depthprediction",
            name="bounding_box",
        ),
        migrations.AddField(
            model_name="depthprediction",
            name="parameters",
            field=models.ForeignKey(
                default=2062402,
                on_delete=django.db.models.deletion.CASCADE,
                to="calculations.floodmodelparameters",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aggregateddepthprediction",
            name="aggregation_level",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="depthprediction",
            name="mid_lower_centile",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="depthprediction",
            name="model_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="calculations.modelversion",
            ),
        ),
    ]
