# Generated by Django 4.0.2 on 2022-02-22 15:07

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculations", "0002_noaaforecast_relative_humidity"),
    ]

    operations = [
        migrations.AddField(
            model_name="noaaforecast",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(0, 0), srid=4326
            ),
        ),
    ]
