# Generated by Django 4.0.3 on 2022-04-08 16:23

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.collections
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculations", "0002_remove_depthprediction_bounding_box_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiverChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_location",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        default=django.contrib.gis.geos.collections.MultiPolygon(),
                        srid=4326,
                    ),
                ),
            ],
        ),
    ]
