# Generated by Django 4.0.2 on 2022-03-01 13:14

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculations", "0003_noaaforecast_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="InitialCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        default=django.contrib.gis.geos.point.Point(0, 0), srid=4326
                    ),
                ),
                ("storage_level", models.FloatField()),
                ("slow_flow_rate", models.FloatField()),
                ("fast_flow_rate", models.FloatField()),
            ],
        ),
    ]
