# Generated by Django 4.0.2 on 2022-03-04 12:10

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculations", "0004_initialcondition"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiverFlowsForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        default=django.contrib.gis.geos.point.Point(0, 0), srid=4326
                    ),
                ),
                ("rain_fall", models.FloatField()),
                ("potential_evapotranspiration", models.FloatField()),
            ],
        ),
    ]
