# Generated by Django 4.0.2 on 2022-03-08 13:51

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculations", "0005_riverflowcalculationoutput_riverflowprediction"),
    ]

    operations = [
        migrations.CreateModel(
            name="AggregatedDepthPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prediction_date", models.DateTimeField()),
                (
                    "lower_bound",
                    django.contrib.gis.db.models.fields.PointField(
                        default=django.contrib.gis.geos.point.Point(0, 0), srid=4326
                    ),
                ),
                (
                    "upper_bound",
                    django.contrib.gis.db.models.fields.PointField(
                        default=django.contrib.gis.geos.point.Point(0, 0), srid=4326
                    ),
                ),
                ("median_depth", models.FloatField()),
                ("centile_25", models.FloatField()),
                ("centile_75", models.FloatField()),
            ],
        ),
    ]
