# Generated by Django 4.0.2 on 2022-03-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculations", "0006_potentialriverflows_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="potentialriverflows",
            name="forecast_hour",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rainandevapotranspiration",
            name="forecast_hour",
            field=models.IntegerField(default=0),
        ),
    ]
