# Generated by Django 4.0.2 on 2022-03-08 14:17

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculations", "0006_alter_noaaforecast_relative_humidity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AggregatedZentraReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        default=django.contrib.gis.geos.point.Point(0, 0), srid=4326
                    ),
                ),
                ("precipitation", models.FloatField()),
                ("min_temperature", models.FloatField()),
                ("max_temperature", models.FloatField()),
                ("wind_u", models.FloatField()),
                ("wind_v", models.FloatField()),
                ("relative_humidity", models.FloatField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="noaaforecast",
            name="relative_humidity",
            field=models.FloatField(default=0),
        ),
    ]
