# Generated by Django 4.0.2 on 2022-03-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calculations",
            "0009_rename_centile_25_aggregateddepthprediction_lower_centile_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PercentageFloodRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prediction_date", models.DateTimeField()),
                ("percentage_risk", models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name="aggregateddepthprediction",
            name="mid_lower_centile",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
