# Generated by Django 4.0.2 on 2022-03-29 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculations", "0010_percentagefloodrisk_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="percentagefloodrisk",
            old_name="percentage_risk",
            new_name="risk",
        ),
    ]
