# Generated by Django 4.0.3 on 2022-04-01 10:43

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.polygon
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "calculations",
            "0012_rename_prediction_date_aggregateddepthprediction_date_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_name", models.CharField(max_length=50)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("is_current", models.BooleanField()),
                ("param_file", models.FileField(upload_to="params/")),
            ],
        ),
        migrations.CreateModel(
            name="FloodModelParameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bounding_box",
                    django.contrib.gis.db.models.fields.PolygonField(
                        default=django.contrib.gis.geos.polygon.Polygon(
                            ((0, 0), (0, 1), (1, 1), (1, 0), (0, 0))
                        ),
                        srid=4326,
                    ),
                ),
                ("beta0", models.FloatField()),
                ("beta1", models.FloatField(null=True)),
                ("beta2", models.FloatField(null=True)),
                ("beta3", models.FloatField(null=True)),
                ("beta4", models.FloatField(null=True)),
                ("beta5", models.FloatField(null=True)),
                ("beta6", models.FloatField(null=True)),
                ("beta7", models.FloatField(null=True)),
                ("beta8", models.FloatField(null=True)),
                ("beta9", models.FloatField(null=True)),
                ("beta10", models.FloatField(null=True)),
                ("beta11", models.FloatField(null=True)),
                ("beta12", models.FloatField(null=True)),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculations.modelversion",
                    ),
                ),
            ],
        ),
    ]
