# Generated by Django 4.0.3 on 2022-04-01 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculations", "0014_aggregateddepthprediction_model_version"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AggregatedDepthPrediction",
            new_name="DepthPrediction",
        ),
    ]
