# Generated by Django 4.0.3 on 2022-04-01 14:46

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.polygon
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calculations", "0015_rename_aggregateddepthprediction_depthprediction"),
    ]

    operations = [
        migrations.CreateModel(
            name="AggregatedDepthPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "bounding_box",
                    django.contrib.gis.db.models.fields.PolygonField(
                        default=django.contrib.gis.geos.polygon.Polygon(
                            ((0, 0), (0, 1), (1, 1), (1, 0), (0, 0))
                        ),
                        srid=4326,
                    ),
                ),
                ("median_depth", models.FloatField()),
                ("lower_centile", models.FloatField()),
                ("mid_lower_centile", models.FloatField()),
                ("upper_centile", models.FloatField()),
                ("tile_size", models.FloatField()),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculations.modelversion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
