# Generated by Django 4.0.3 on 2022-04-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculations", "0016_aggregateddepthprediction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aggregateddepthprediction",
            name="tile_size",
        ),
        migrations.AddField(
            model_name="aggregateddepthprediction",
            name="aggregation_level",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
