# Generated by Django 4.0 on 2022-01-26 15:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccumulatedRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cat", models.BigIntegerField()),
                ("value", models.FloatField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPointField(srid=4362),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cat", models.BigIntegerField()),
                ("value", models.BigIntegerField()),
                ("label", models.CharField(max_length=10, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiLineStringField(srid=4362),
                ),
            ],
        ),
    ]
