# Generated by Django 4.0.2 on 2022-03-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useralert",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="useralert",
            name="alert_type",
            field=models.CharField(
                choices=[("sms", "SMS")], default="sms", max_length=8
            ),
        ),
    ]
