version: '3.6'

services:

  # Web server container
  web:
    image: durhamarc/manyfews-web:azure-latest
    container_name: ${COMPOSE_PROJECT_NAME}_web
    restart: always
    environment:
      UPSTREAM_SERVER: ${UPSTREAM_SERVER}
      UPSTREAM_PORT: ${UPSTREAM_PORT}
    ports:
      - "80:80/tcp"
    networks:
      - default

# Define networks and volumes
networks:
  default:

volumes:
  uploads:
