"""
Django settings for manyfews project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import environ

# Initialise environment variables
env = environ.Env()
environ.Env.read_env()

ZENTRA_UN = env("zentra_un")
ZENTRA_PW = env("zentra_pw")
LAT_VALUE = env("latValue")
LON_VALUE = env("lonValue")
ZENTRA_BACKTIME = env("zentra_backtime")
STATION_SN = env("station_SN")
GEFS_TIME_STEP = env("gefs_timestep")
GEFS_FORECAST_DAYS = env("gefs_forecastDays")
MAP_API_TOKEN = env("map_api_token")

# Email settings
EMAIL_HOST = env("email_host")
EMAIL_PORT = env("email_port")
EMAIL_HOST_USER = env("email_host_user")
EMAIL_HOST_PASSWORD = env("email_host_password")
EMAIL_USE_SSL = env("email_use_ssl")

# Twilio settings (for SMS/WhatsApp)
TWILIO_ACCOUNT_SID = env("twilio_account_sid")
TWILIO_AUTH_TOKEN = env("twilio_auth_token")
TWILIO_PHONE_NUMBER = env("twilio_phone_number")
TWILIO_VERIFICATION_SID = env("twilio_verification_sid")

# Site URL (or short URL) for use in messages
SITE_URL = env.str("site_url", "http://localhost:8000")

# Text to use in alerts. Will be populated with max_depth, start and end dates and SITE_URL
ALERT_TEXT = env.str(
    "alert_text",
    "Floods up to {max_depth}m predicted from {start_date} to {end_date}. See {site_url} for details.",
)
# Date string to use in alerts: for formats see https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes
ALERT_DATE_FORMAT = env.str("alert_date_format", "%b %d")
ALERT_DEPTH_THRESHOLD = env.float("alert_depth_threshold", 0.1)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-jau(^3c!z+wl6#zsz!%bu1$v7ks48dosj1#=l=^+58)r1y2n8b"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    "django_celery_beat",
    "crispy_forms",
    "djgeojson",
    "leaflet",
    "phonenumber_field",
    "calculations",
    "webapp",
    "accounts",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "manyfews.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [str(BASE_DIR.joinpath("templates"))],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "webapp.context_processors.include_login_form",
            ],
        },
    },
]

WSGI_APPLICATION = "manyfews.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": "manyfews",
        "USER": "manyfews",
        "PASSWORD": "manyfews",
        "HOST": "localhost",
        "PORT": 5432,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CRISPY_TEMPLATE_PACK = "bootstrap4"

LEAFLET_CONFIG = {
    "DEFAULT_CENTER": (-7.052115, 107.755514),
    "DEFAULT_ZOOM": 16,
    "MIN_ZOOM": 10,
    "MAX_ZOOM": 25,
    "DEFAULT_PRECISION": 6,
    "TILES": f"https://api.mapbox.com/styles/v1/mapbox/streets-v11/tiles/{{z}}/{{x}}/{{y}}?access_token={MAP_API_TOKEN}",
}

CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
