name: Hello World
on: push
jobs:
  my_first_job:
    name: My first job
    runs-on: macos-10.15
    steps:
    - name: Run a multi-line script
      env:
        MY_VAR: Hello World!
        MY_NAME: Abel_Tu
      run: |
        echo $MY_VAR
        echo My name is $MY_NAM


