on: push
jobs:
  my_first_job:
    name: My first job
    runs-on: macos-10.15
    steps:
    - name: Run a multi-line script
      env:
        MY_VAR: Hello World!
        MY_NAME: Abel_Tu
    - name: Set up Python 3.9.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
      run: |
        echo $MY_VAR
        echo My name is $MY_NAME
        python
