name: Hello World
on: push
jobs:
  my_first_job:
    name: My first job
    runs-on: macos-10.15
    steps:
    - uses: actions/setup-python@v2
    with:
    python-version: '3.9.7' 
    architecture: 'x64' 
    - run: python


