name: set up python environment
on: push

jobs:
  setEnv:
    name: set up python conda environment and run
    runs-on: macos-10.15
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        rev: 19.10b0
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: anaconda-client-env
          environment-file: condaEnv/manyFEMSenv.yml
          python-version: 3.9
          auto-activate-base: false
      - run: |
          conda info
          conda list
      - name: run test script 'test_GenerateRiverFlows.py'
        run: |
          pytest ./test_manyFEMS/unit/test_GeneraterRiverFlow/test_GenerateRiverFlows.py
