name: set up python environment
on: push

jobs:
  setEnv:
    name: set up python conda environment
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: "ubuntu-latest"
            lock-file: "conda_locks/conda-linux-64.lock"
          - os: "macos-latest"
            lock-file: "conda_locks/conda-osx-64.lock"
          - os: "windows-latest"
            lock-file: "conda_locks/conda-win-64.lock"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          activate-environment: explicit-env
          environment-file: ${{ matrix.lock-file }}
      - run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort

