name: set up python environment
on: push

jobs:
  setEnv:
    name: set up python conda environment
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          activate-environment: explicit-env
          environment-file: ./condaEnv/manyFEMSdependency.yml

      - name: check Python dependencies
        run: |
          which python
          source activate manyFEWS
          which python

      - name: test python environment and 'hello world' CI
        run: |
          which python
          echo hellow world
          python GenerateRiverFlows/hellow_world.py

      - name: run script 'GenerateRiverFlows.py'
        run: |
          cd GenerateRiverFlows
          python GenerateRiverFlows.py



