name: set up python environment
on: push
jobs:
  my-job:
    name: set up python3
    runs-on: macos-10.15
    steps:
    - name: Set up Python 3.8
    - uses: actions/setup-python@v2
      with:
      python-version: 3.8
    - run: python -v



