name: set up python environment
on: push

jobs:
  setEnv:
    name: set up python conda environment
    runs-on: macos-10.15
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: s-weigand/setup-conda@v1
        with:
          activate-conda: true
      - run: |
          conda --version
          which python
          conda create -n manyFEMS python=3.9
          conda install numpy
          conda install xlrd
          conda list
          conda init bash
          conda activate manyFEMS

